Mobile-portfolio
richie1988/MOBILE-POTFOLIO pull request #1
Opened 2023-03-28 14:37 UTC by richie1988

added the Logo 
added the text 
added social handle
added navigation icon

2023-03-28 15:55 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @richie1988, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 15:55 UTC, bobb-Rob commented on README.md
> +This project is [MIT](.MIT.md) licensed.
- [ ] The link MIT currently leads to a 404 page. I noticed that line 159 in your README file has the wrong file path for the MIT file. It should be (./MIT) and not (.MIT).

Please fix this.

2023-03-28 15:55 UTC, bobb-Rob commented on index.html
> +        </div>
- [ ] The container of this toolbar should be a `<header>` tag and not a `<div>`. Typically the `header` tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info. 
- [ ] The toolbar/navbar should use CSS flexbox to align its contents.

Kindly fix this

2023-03-28 15:55 UTC, bobb-Rob commented on index.html
> +        </div>
Your website should look exactly like the design (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Compare the Figma design and your work below. You will see some issue that needs to be fixed.

- [ ] The hamburger button should be on the right and has a `nav` tag.  The `nav` tag is for semantics reason, and the right position for convention and user experience for mobile devices.
- [ ] Please remove the other three nav links because it is not part of the project requirement for this milestone. You will have the chance to add them when you are implementing the desktop view.
- [ ] This `<h1>I’m Richard Sikaonga.<br>Glad to see you!</h1>` and the paragraph `<p>I’m a software developer!...` should be aligned to the left of the page as seen in the Figma design.

Figma Design | Your work
---- | ---- 
![image](https://user-images.githubusercontent.com/84156714/228290812-2b365f55-9112-493a-9b75-86dbb413d280.png) | ![image](https://user-images.githubusercontent.com/84156714/228289188-ce91e62d-066d-4585-a306-928a116075fc.png)

2023-03-28 15:55 UTC, bobb-Rob commented on index.html
> +            <a href="#social"><img src="icon/angellist (1).svg"></a>
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag). You have already added the `a` tag. Please wrap all of them in their respective `li` tags as this will further improve your page accessibility.
- [ ] Also, make the social media icons size the same as seen in the figma design

Your work
![image](https://user-images.githubusercontent.com/84156714/228295274-495d4052-6206-4bd0-8fba-8aafc30d0d2e.png)

Figma
![image](https://user-images.githubusercontent.com/84156714/228295355-fb6c750a-e388-407f-a133-2f4d23327a7f.png)

2023-03-28 15:55 UTC, bobb-Rob commented on index.html
> +        </div>
- [ ] The headline section should use a `section` tag as its container. It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info. 
- [ ] This headline section contents should be aligned using CSS flexbox. This is a core requirement. Kindly use it
- [ ] The section should have the proper background image (decorations are always background images, not `img` tags). As a rule of thumb, if an image is not part of the content (aesthetic reasons) use CSS background-image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info. Kindly add the background image.

2023-03-30 11:33 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :
Hi @richie1988 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif">

 ## Highlights :tophat: :+1: 
- No linter errors :100: 

 ## Required Changes ♻️
- [OPTIONAL] Kindly make sure to respect GitHub flow , by creating a merge request from feature to main/master:+1:  
_Check the comments under the review._

## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 11:33 UTC, GedeonTS commented on style.css
> +}
- [ ] As requested by the previous reviewer, kindly make sure your elements are laid out using flexbox :recycle:

2023-03-30 11:46 UTC, richie1988 commented on style.css
> +/* stylelint-disable indentation */
hello kindly explain to me what i need to change and were should i implement the changes please more in detail

2023-03-30 11:57 UTC, richie1988 commented on style.css
> +/* stylelint-disable indentation */
hello do i need to add all item inside the div tag or should i use display flex?

2023-03-30 14:34 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @richie1988  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the Figma design ☑️ 
- Project Documentation (PR, README) is professional :necktie: 

Congrats on your work so far! :clap:  

## Required Changes ♻️

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2023-03-30 14:34 UTC, Nyame-Wolf commented on style.css
> +/* stylelint-disable indentation */
As suggested by the previous reviewer, Kindly fix the errors you have on your style sheet instead of disabling linter checks.
Linters help you write code that is industry standard and free of errors
Read more [here](https://www.makeuseof.com/what-is-linting/#:~:text=Helps%20Check%20for%20Errors,other%20issues%20that%20may%20arise.)

2023-03-30 14:34 UTC, Nyame-Wolf commented on style.css
> +body {
I can see you changed the template you were using before to template 2, however, your project has margins that are not present in the original project. As per the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md) your project should look exactly as figma design. This is your project
<img width="1537" alt="Screenshot 2023-03-30 at 17 19 31" src="https://user-images.githubusercontent.com/48546992/228869991-c9222055-9dc7-4f98-939e-28565435c472.png">
I suggest you add 
`margin : 0` to your body element.
For your project to look like this
<img width="376" alt="Screenshot 2023-03-30 at 17 22 27" src="https://user-images.githubusercontent.com/48546992/228870247-f9838a53-d4f6-456e-af1f-98de6a5823d1.png">

2023-03-30 17:40 UTC, richie1988 commented on style.css
> +body {
hello please i have tried to fix the issue for identition do you know how to fix this issue? inside the vscode

2023-03-30 17:41 UTC, richie1988 commented on style.css
> +body {
the stylelint inside the vscode as the problem its keep on ggiving me this problem

2023-03-30 19:26 UTC, richie1988 commented on style.css
> +/* stylelint-disable indentation */
its not the style sheet problem its vscode i have checked all its saying spelling erros

2023-04-25 11:24 UTC, Nyame-Wolf requested changes
# STATUS: INVALID CODE REVIEW :x: :stop_sign:  

Hi @richie1988 >, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :warning:

You have submitted a project, that does no correspond to the project. Note that this is the hello microverse project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Make it work and then make it better!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-25 11:26 UTC, richie1988 commented
noticed that sorry for that

2023-04-25 11:53 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @richie1988 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- [ ] Kindly ensure to follow the correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md). The pull request should be `into` master from `feature-branch`.
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-04-25 11:56 UTC, merged